use_frameworks!

platform :ios, '16.0'

target 'LocationKitProject_Example' do
  pod 'LocationKitProject', :path => '../'

  target 'LocationKitProject_Tests' do
    inherit! :search_paths

    
  end
end
